import { createClient } from '@supabase/supabase-js'

export const supabase = createClient('https://lqkborcslpyefkdhpjvo.supabase.co', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxxa2JvcmNzbHB5ZWZrZGhwanZvIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY5NjM1NDM1NiwiZXhwIjoyMDExOTMwMzU2fQ.qLhankyO5QCcHfj-pqDsLKw8IqNnidxuxJgBz_hto3g')